"$schema" = 'https://starship.rs/config-schema.json'

format = "$os$username$directory$git_branch$git_status$character"
add_newline = false

palette = 'tokyo_like'

[palettes.tokyo_like]
cyan = '#9fd6f4'
pink = '#f776c6'
green = '#8ef0a1'
yellow = '#e6d37a'
red = '#ff757f'
muted = '#c0caf5'

[os]
disabled = false
style = "fg:cyan"
format = "[$symbol ]($style)"

[os.symbols]
Macos = "󰀵"
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "fg:cyan"
style_root = "fg:red"
format = "[$user ]($style)"

[directory]
style = "fg:yellow"
truncation_length = 3
truncation_symbol = ".../"
format = "[$path ]($style)"

[git_branch]
symbol = " "
style = "fg:pink"
format = "[$symbol$branch]($style) "

[git_status]
style = "fg:muted"
format = "[$all_status$ahead_behind]($style) "

[character]
success_symbol = "[❯](fg:green)"
error_symbol = "[❯](fg:red)"
vimcmd_symbol = "[❮](fg:green)"
vimcmd_replace_one_symbol = "[❮](fg:pink)"
vimcmd_replace_symbol = "[❮](fg:pink)"
vimcmd_visual_symbol = "[❮](fg:yellow)"
